// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWUiky2lJX785W6JHkboqrx7ImmofAE4',
    appId: '1:745223836964:web:59e13a634aa6b87345cfb1',
    messagingSenderId: '745223836964',
    projectId: 'minimalchatapp-a12a1',
    authDomain: 'minimalchatapp-a12a1.firebaseapp.com',
    storageBucket: 'minimalchatapp-a12a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsmDu8gRnLLPw9yNaQ-0AfwRqR6Juzn40',
    appId: '1:745223836964:android:d0e22037cc9548ad45cfb1',
    messagingSenderId: '745223836964',
    projectId: 'minimalchatapp-a12a1',
    storageBucket: 'minimalchatapp-a12a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn79H6pOkRb4QeiDecS_JpERSWeZYpGDU',
    appId: '1:745223836964:ios:e59c4d07d49d9b7745cfb1',
    messagingSenderId: '745223836964',
    projectId: 'minimalchatapp-a12a1',
    storageBucket: 'minimalchatapp-a12a1.appspot.com',
    iosBundleId: 'com.example.minimal1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn79H6pOkRb4QeiDecS_JpERSWeZYpGDU',
    appId: '1:745223836964:ios:6081ef530dc0af8445cfb1',
    messagingSenderId: '745223836964',
    projectId: 'minimalchatapp-a12a1',
    storageBucket: 'minimalchatapp-a12a1.appspot.com',
    iosBundleId: 'com.example.minimal1.RunnerTests',
  );
}
